/* eslint-disable @next/next/no-img-element */
"use client";

import Cropper, { type Area } from "react-easy-crop";
import { useMemo, useRef, useState } from "react";
import { formatMoney } from "@/lib/format-money";

type Category = { categoryId: number; name: string; sortOrder: number };
type Menu = { menuId: number; menuCode: string; name: string; price: string; categoryId: number | null; categoryName: string; categorySortOrder: number; countsAsPerson: number; isActive: number; sortOrder: number; imageUrl: string | null };
type MenuPayload = { name: string; price: string; categoryId: number; countsAsPerson: boolean; isActive: boolean };

const categoryDisplayName = (name: string) => ({ "김치찌개": "찌개", "사이드": "단품", "주류·음료": "음료" }[name] ?? name);
const parsePrice = (value: string) => Number(value.replaceAll(",", "").trim());
const formatPriceInput = (value: string | number) => new Intl.NumberFormat("ko-KR", { maximumFractionDigits: 2 }).format(Number(value));
const sortMenus = (items: Menu[]) => [...items].sort((a, b) => a.categorySortOrder - b.categorySortOrder || a.sortOrder - b.sortOrder || a.menuId - b.menuId);

export default function MenuManagementClient({ categories, initialMenus }: { categories: Category[]; initialMenus: Menu[] }) {
  const [activeCategoryId, setActiveCategoryId] = useState<number | null>(null);
  const [menuRows, setMenuRows] = useState(() => sortMenus(initialMenus));
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [editingMenu, setEditingMenu] = useState<Menu | null>(null);
  const [message, setMessage] = useState("");
  const [movingMenuId, setMovingMenuId] = useState<number | null>(null);
  const visibleGroups = useMemo(() => categories.filter(category => activeCategoryId === null || category.categoryId === activeCategoryId).map(category => ({ category, menus: menuRows.filter(menu => menu.categoryId === category.categoryId) })), [activeCategoryId, categories, menuRows]);

  const moveMenu = async (menu: Menu, direction: "up" | "down") => {
    setMovingMenuId(menu.menuId); setMessage("");
    try {
      const response = await fetch("/api/admin/menus/order", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ menuId: menu.menuId, direction }) });
      const result = await response.json() as { success?: boolean; message?: string; sortOrders?: { menuId: number; sortOrder: number }[] };
      if (!response.ok || !result.success || !result.sortOrders) throw new Error(result.message ?? "메뉴 순서를 변경할 수 없습니다.");
      const orders = new Map(result.sortOrders.map(item => [item.menuId, item.sortOrder]));
      setMenuRows(current => sortMenus(current.map(item => orders.has(item.menuId) ? { ...item, sortOrder: orders.get(item.menuId)! } : item)));
    } catch (error) { setMessage(error instanceof Error ? error.message : "메뉴 순서를 변경할 수 없습니다."); } finally { setMovingMenuId(null); }
  };
  const addMenu = async (payload: MenuPayload) => {
    const response = await fetch("/api/admin/menus", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
    const result = await response.json() as { success?: boolean; message?: string; menu?: Menu };
    if (!response.ok || !result.success || !result.menu) throw new Error(result.message ?? "메뉴를 등록할 수 없습니다.");
    setMenuRows(current => sortMenus([...current, result.menu!])); setActiveCategoryId(payload.categoryId); setIsCreateOpen(false); setMessage("새 메뉴를 등록했습니다.");
  };
  const updateMenu = async (menuId: number, form: FormData, categoryId: number) => {
    const response = await fetch("/api/admin/menus/" + menuId, { method: "PATCH", body: form });
    const result = await response.json() as { success?: boolean; message?: string; menu?: Menu };
    if (!response.ok || !result.success || !result.menu) throw new Error(result.message ?? "메뉴를 수정할 수 없습니다.");
    setMenuRows(current => sortMenus(current.map(item => item.menuId === menuId ? result.menu! : item))); setActiveCategoryId(categoryId); setEditingMenu(null); setMessage("메뉴를 수정했습니다.");
  };

  return <section className="mx-auto mt-6 max-w-6xl">
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-white p-4 shadow-sm">
      <div className="flex flex-wrap gap-2"><button className={activeCategoryId === null ? activeClass : idleClass} onClick={() => setActiveCategoryId(null)} type="button">전체</button>{categories.map(category => <button className={activeCategoryId === category.categoryId ? activeClass : idleClass} key={category.categoryId} onClick={() => setActiveCategoryId(category.categoryId)} type="button">{categoryDisplayName(category.name)}</button>)}</div>
      <button className={activeClass + " disabled:bg-slate-300"} disabled={!categories.length} onClick={() => setIsCreateOpen(true)} type="button">+ 새 메뉴 추가</button>
    </div>
    {message && <p className="mt-3 text-sm font-semibold text-blue-700">{message}</p>}
    <div className="mt-4 space-y-4">{visibleGroups.map(group => <MenuGroup category={group.category} editMenu={setEditingMenu} key={group.category.categoryId} menus={group.menus} moveMenu={moveMenu} movingMenuId={movingMenuId} />)}</div>
    {isCreateOpen && <CreateMenuDialog categories={categories} close={() => setIsCreateOpen(false)} create={addMenu} defaultCategoryId={activeCategoryId ?? categories[0]?.categoryId ?? 0} />}
    {editingMenu && <EditMenuDialog categories={categories} close={() => setEditingMenu(null)} menu={editingMenu} update={updateMenu} />}
  </section>;
}

const activeClass = "min-h-11 rounded-xl bg-blue-600 px-4 font-bold text-white";
const idleClass = "min-h-11 rounded-xl border border-slate-300 bg-white px-4 font-bold text-slate-700";

function MenuGroup({ category, menus, movingMenuId, moveMenu, editMenu }: { category: Category; menus: Menu[]; movingMenuId: number | null; moveMenu: (menu: Menu, direction: "up" | "down") => Promise<void>; editMenu: (menu: Menu) => void }) {
  return <section className="overflow-x-auto rounded-2xl bg-white shadow-sm"><h2 className="border-b border-slate-200 px-5 py-4 text-lg font-extrabold">{categoryDisplayName(category.name)}</h2><div className="min-w-[720px]">
    <div className="grid grid-cols-[56px_minmax(0,1fr)_110px_90px_88px_108px] gap-3 border-b border-slate-200 bg-slate-50 px-5 py-3 text-xs font-bold text-slate-500"><span>순서</span><span>메뉴명</span><span className="text-right">가격</span><span>카테고리</span><span>사용 상태</span><span className="text-center">순서 변경</span></div>
    {menus.length ? menus.map((menu, index) => <div className="grid min-h-14 cursor-pointer grid-cols-[56px_minmax(0,1fr)_110px_90px_88px_108px] items-center gap-3 border-b border-slate-100 px-5 py-2 last:border-b-0 hover:bg-slate-50" key={menu.menuId} onClick={() => editMenu(menu)} role="button" tabIndex={0}>
      <span className="font-bold text-slate-500">{index + 1}</span><span className="truncate font-bold">{menu.name}</span><span className="text-right font-semibold text-blue-700">{formatMoney(menu.price)}</span><span className="truncate text-slate-600">{categoryDisplayName(menu.categoryName)}</span><span className={menu.isActive ? "font-semibold text-emerald-700" : "font-semibold text-slate-400"}>{menu.isActive ? "사용 중" : "사용 안 함"}</span><span className="flex justify-center gap-2"><button aria-label={menu.name + " 위로 이동"} className="min-h-10 min-w-10 rounded-lg border border-slate-300 bg-white font-bold disabled:cursor-not-allowed disabled:text-slate-300" disabled={index === 0 || movingMenuId !== null} onClick={event => { event.stopPropagation(); void moveMenu(menu, "up"); }} type="button">↑</button><button aria-label={menu.name + " 아래로 이동"} className="min-h-10 min-w-10 rounded-lg border border-slate-300 bg-white font-bold disabled:cursor-not-allowed disabled:text-slate-300" disabled={index === menus.length - 1 || movingMenuId !== null} onClick={event => { event.stopPropagation(); void moveMenu(menu, "down"); }} type="button">↓</button></span>
    </div>) : <p className="px-5 py-8 text-sm text-slate-400">등록된 메뉴가 없습니다.</p>}
  </div></section>;
}

function CreateMenuDialog({ categories, defaultCategoryId, close, create }: { categories: Category[]; defaultCategoryId: number; close: () => void; create: (payload: MenuPayload) => Promise<void> }) {
  const [name, setName] = useState(""); const [price, setPrice] = useState(""); const [categoryId, setCategoryId] = useState(defaultCategoryId); const [countsAsPerson, setCountsAsPerson] = useState(false); const [isActive, setIsActive] = useState(true); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const submit = async () => { if (!name.trim() || !price.trim() || !Number.isFinite(Number(price))) { setError("메뉴명, 가격, 카테고리를 확인하세요."); return; } setSaving(true); setError(""); try { await create({ name: name.trim(), price, categoryId, countsAsPerson, isActive }); } catch (reason) { setError(reason instanceof Error ? reason.message : "메뉴를 등록할 수 없습니다."); } finally { setSaving(false); } };
  return <Dialog close={close} saving={saving} title="새 메뉴 추가"><label className="mt-5 block text-sm font-bold">메뉴명 *<input autoFocus className={inputClass} maxLength={150} onChange={event => setName(event.target.value)} value={name} /></label><label className="mt-4 block text-sm font-bold">가격 *<span className="mt-2 flex items-center gap-2"><input className={inputClass + " text-right"} inputMode="decimal" onChange={event => setPrice(event.target.value)} value={price} /></span></label><CategorySelect categories={categories} categoryId={categoryId} setCategoryId={setCategoryId} /><Toggles countsAsPerson={countsAsPerson} isActive={isActive} setCountsAsPerson={setCountsAsPerson} setIsActive={setIsActive} />{error && <p className="mt-4 text-sm font-semibold text-red-600">{error}</p>}<DialogFooter cancel={close} saving={saving} submit={submit} submitText="메뉴 추가" /></Dialog>;
}

function EditMenuDialog({ categories, close, menu, update }: { categories: Category[]; close: () => void; menu: Menu; update: (menuId: number, form: FormData, categoryId: number) => Promise<void> }) {
  const [name, setName] = useState(menu.name); const [price, setPrice] = useState(formatPriceInput(menu.price)); const [categoryId, setCategoryId] = useState(menu.categoryId ?? categories[0]?.categoryId ?? 0); const [countsAsPerson, setCountsAsPerson] = useState(menu.countsAsPerson === 1); const [isActive, setIsActive] = useState(menu.isActive === 1); const [previewUrl, setPreviewUrl] = useState(menu.imageUrl); const [croppedImage, setCroppedImage] = useState<File | null>(null); const [removeImage, setRemoveImage] = useState(false); const [cropSource, setCropSource] = useState<string | null>(null); const [crop, setCrop] = useState({ x: 0, y: 0 }); const [zoom, setZoom] = useState(1); const [cropPixels, setCropPixels] = useState<Area | null>(null); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const inputRef = useRef<HTMLInputElement>(null);
  const selectImage = (file: File | undefined) => { if (!file) return; if (!["image/jpeg", "image/png", "image/webp"].includes(file.type) || file.size > 10 * 1024 * 1024) { setError("JPG, PNG, WebP 형식의 10MB 이하 이미지를 선택하세요."); return; } setError(""); setCropSource(URL.createObjectURL(file)); setZoom(1); };
  const applyCrop = async () => { if (!cropSource || !cropPixels) return; try { const image = new Image(); image.src = cropSource; await image.decode(); const canvas = document.createElement("canvas"); canvas.width = 1200; canvas.height = 1200; const context = canvas.getContext("2d"); if (!context) throw new Error("이미지를 처리할 수 없습니다."); context.drawImage(image, cropPixels.x, cropPixels.y, cropPixels.width, cropPixels.height, 0, 0, 1200, 1200); const blob = await new Promise<Blob>((resolve, reject) => canvas.toBlob(result => result ? resolve(result) : reject(new Error("이미지를 처리할 수 없습니다.")), "image/webp", 0.92)); setCroppedImage(new File([blob], "menu-crop.webp", { type: "image/webp" })); setPreviewUrl(URL.createObjectURL(blob)); setRemoveImage(false); setCropSource(null); } catch (reason) { setError(reason instanceof Error ? reason.message : "이미지를 자를 수 없습니다."); } };
  const submit = async () => { const numericPrice = parsePrice(price); if (!name.trim() || !Number.isFinite(numericPrice) || !Number.isInteger(categoryId)) { setError("메뉴명, 가격, 카테고리를 확인하세요."); return; } const form = new FormData(); form.set("name", name.trim()); form.set("price", String(numericPrice)); form.set("categoryId", String(categoryId)); form.set("countsAsPerson", String(countsAsPerson)); form.set("isActive", String(isActive)); form.set("removeImage", String(removeImage)); if (croppedImage) form.set("image", croppedImage); setSaving(true); setError(""); try { await update(menu.menuId, form, categoryId); } catch (reason) { setError(reason instanceof Error ? reason.message : "메뉴를 수정할 수 없습니다."); } finally { setSaving(false); } };
  return <><Dialog close={close} saving={saving} title="메뉴 수정"><label className="mt-5 block text-sm font-bold">메뉴명 *<input autoFocus className={inputClass} maxLength={150} onChange={event => setName(event.target.value)} value={name} /></label><label className="mt-4 block text-sm font-bold">가격 *<span className="mt-2 flex items-center gap-2"><input className={inputClass + " text-right"} inputMode="decimal" onBlur={() => { const value = parsePrice(price); if (Number.isFinite(value)) setPrice(formatPriceInput(value)); }} onChange={event => setPrice(event.target.value.replace(/[^\d,.-]/g, ""))} value={price} /><span>원</span></span></label><CategorySelect categories={categories} categoryId={categoryId} setCategoryId={setCategoryId} /><ImageEditor inputRef={inputRef} previewUrl={previewUrl} remove={() => { setCroppedImage(null); setPreviewUrl(null); setRemoveImage(true); }} select={() => inputRef.current?.click()} selectImage={selectImage} /><Toggles countsAsPerson={countsAsPerson} isActive={isActive} setCountsAsPerson={setCountsAsPerson} setIsActive={setIsActive} />{error && <p className="mt-4 text-sm font-semibold text-red-600">{error}</p>}<DialogFooter cancel={close} saving={saving} submit={submit} submitText="저장" /></Dialog>{cropSource && <CropDialog apply={() => void applyCrop()} crop={crop} cropSource={cropSource} setCrop={setCrop} setCropSource={setCropSource} setZoom={setZoom} zoom={zoom} onCropComplete={(_croppedArea, croppedAreaPixels) => setCropPixels(croppedAreaPixels)} />}</>;
}

const inputClass = "mt-2 min-h-11 w-full rounded-lg border border-slate-300 px-3";
function Dialog({ close, saving, title, children }: { close: () => void; saving: boolean; title: string; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" onClick={() => !saving && close()}><section aria-modal="true" className="relative max-h-[92dvh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-6 shadow-xl" onClick={event => event.stopPropagation()} role="dialog"><button aria-label="닫기" className="absolute right-4 top-4 min-h-10 min-w-10 rounded-lg text-xl font-bold text-slate-500 hover:bg-slate-100" disabled={saving} onClick={close} type="button">×</button><h2 className="text-xl font-extrabold">{title}</h2>{children}</section></div>; }
function CategorySelect({ categories, categoryId, setCategoryId }: { categories: Category[]; categoryId: number; setCategoryId: (value: number) => void }) { return <label className="mt-4 block text-sm font-bold">카테고리 *<select className={inputClass} onChange={event => setCategoryId(Number(event.target.value))} value={categoryId}>{categories.map(category => <option key={category.categoryId} value={category.categoryId}>{categoryDisplayName(category.name)}</option>)}</select></label>; }
function Toggles({ countsAsPerson, isActive, setCountsAsPerson, setIsActive }: { countsAsPerson: boolean; isActive: boolean; setCountsAsPerson: (value: boolean) => void; setIsActive: (value: boolean) => void }) { return <><label className="mt-5 flex min-h-11 items-center gap-3 font-bold"><input checked={countsAsPerson} className="size-5" onChange={event => setCountsAsPerson(event.target.checked)} type="checkbox" />인원수 메뉴</label><label className="mt-3 flex min-h-11 items-center gap-3 font-bold"><input checked={isActive} className="size-5" onChange={event => setIsActive(event.target.checked)} type="checkbox" />POS 사용</label></>; }
function DialogFooter({ cancel, saving, submit, submitText }: { cancel: () => void; saving: boolean; submit: () => void; submitText: string }) { return <footer className="mt-6 grid grid-cols-2 gap-3"><button className="min-h-12 rounded-xl border border-slate-300 bg-white font-bold" disabled={saving} onClick={cancel} type="button">취소</button><button className="min-h-12 rounded-xl bg-blue-600 font-bold text-white disabled:bg-slate-300" disabled={saving} onClick={submit} type="button">{saving ? "저장 중" : submitText}</button></footer>; }
function ImageEditor({ inputRef, previewUrl, select, selectImage, remove }: { inputRef: React.RefObject<HTMLInputElement | null>; previewUrl: string | null; select: () => void; selectImage: (file: File | undefined) => void; remove: () => void }) { return <section className="mt-5"><h3 className="text-sm font-bold">메뉴 이미지</h3><div className="mt-2 flex items-center gap-4"><div className="flex size-28 items-center justify-center overflow-hidden rounded-xl border border-slate-300 bg-slate-100">{previewUrl ? <img alt="메뉴 이미지 미리보기" className="size-full object-cover" src={previewUrl} /> : <span className="text-xs font-semibold text-slate-400">이미지 없음</span>}</div><div className="flex flex-wrap gap-2"><input accept="image/jpeg,image/png,image/webp" className="hidden" onChange={event => { selectImage(event.target.files?.[0]); event.currentTarget.value = ""; }} ref={inputRef} type="file" /><button className="min-h-11 rounded-lg border border-slate-300 bg-white px-4 font-bold" onClick={select} type="button">이미지 선택</button><button className="min-h-11 rounded-lg border border-slate-300 bg-white px-4 font-bold text-slate-600 disabled:text-slate-300" disabled={!previewUrl} onClick={remove} type="button">이미지 제거</button></div></div></section>; }
function CropDialog({ cropSource, crop, setCrop, zoom, setZoom, onCropComplete, setCropSource, apply }: { cropSource: string; crop: { x: number; y: number }; setCrop: (value: { x: number; y: number }) => void; zoom: number; setZoom: (value: number) => void; onCropComplete: (_area: Area, pixels: Area) => void; setCropSource: (value: string | null) => void; apply: () => void }) { return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/70 p-4"><section className="w-full max-w-xl rounded-2xl bg-white p-5 shadow-2xl"><h2 className="text-xl font-extrabold">이미지 자르기</h2><div className="relative mt-4 h-[min(65dvh,480px)] overflow-hidden rounded-xl bg-slate-900"><Cropper aspect={1} crop={crop} image={cropSource} onCropChange={setCrop} onCropComplete={(_croppedArea, croppedAreaPixels) => onCropComplete(_croppedArea, croppedAreaPixels)} onZoomChange={setZoom} zoom={zoom} /></div><label className="mt-4 flex items-center gap-3 text-sm font-bold">확대/축소<input className="flex-1 accent-blue-600" max="3" min="1" onChange={event => setZoom(Number(event.target.value))} step="0.05" type="range" value={zoom} /></label><footer className="mt-5 grid grid-cols-2 gap-3"><button className="min-h-12 rounded-xl border border-slate-300 bg-white font-bold" onClick={() => setCropSource(null)} type="button">취소</button><button className="min-h-12 rounded-xl bg-blue-600 font-bold text-white" onClick={apply} type="button">적용</button></footer></section></div>; }
